server:
  port: 8080

spring:
  application:
    name: tyapp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  mvc:
    static-path-pattern: /static/**
  freemarker:
    suffix: .html
    template-loader-path: classpath:/views
    content-type: text/html; charset=utf-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  issuer: tyapp
  secret: G5SbV_B8KzrRwo3kz6LwNQ_lpUFV7t9

token:
  expires-in: 1800 #seconds

---
spring:
  profiles: default, dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://106.12.139.252:3306/test_db?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&allowMultiQueries=true
    username: tyuiop
    password: 0okm(IJN
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 30000
    validation-query: select 1
  redis:
    host: 106.12.139.252
    password: tyuiop
    lettuce:
      pool:
          min-idle: 1
          max-wait: 30000




























